# Generated by Django 5.2 on 2025-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('video', models.FileField(upload_to='ads/videos/')),
                ('thumbnail', models.ImageField(upload_to='ads/thumbnails/')),
            ],
        ),
    ]
