# Generated by Django 5.2 on 2025-04-25 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0002_videoad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoAd',
        ),
    ]
