# Generated by Django 5.2 on 2025-04-25 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0004_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='price',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='quantity',
        ),
        migrations.AddField(
            model_name='delivery',
            name='address',
            field=models.TextField(default='default address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='items',
            field=models.TextField(default='No items'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='payment_method',
            field=models.CharField(choices=[('Cash on Delivery', 'Cash on Delivery'), ('GCash', 'GCash')], default='Cash on Delivery', max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
