# Generated by Django 5.2 on 2025-04-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0005_delete_order_remove_delivery_delivery_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
