# Generated by Django 5.2 on 2025-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_alter_delivery_items_alter_delivery_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('items', models.TextField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
